import { TILE_SIZE } from '@/features/rpg/config/constants';
import type { SceneDefinition } from '@/types/rpg';

export const libraryScene: SceneDefinition = {
  id: 'library',
  name: '图书馆',
  width: 18 * TILE_SIZE,
  height: 12 * TILE_SIZE,
  tileSize: TILE_SIZE,
  baseTile: 'library',
  spawnPoints: {
    entry: { x: 8 * TILE_SIZE, y: 9 * TILE_SIZE },
    fromBlog: { x: 3 * TILE_SIZE, y: 9 * TILE_SIZE },
    fromStacks: { x: 12.2 * TILE_SIZE, y: 3.4 * TILE_SIZE },
  },
  decorations: [
    { id: 'reading-rug', name: '阅览地毯', type: 'decoration', x: 4.8 * TILE_SIZE, y: 3.7 * TILE_SIZE, w: 8.2 * TILE_SIZE, h: 4.1 * TILE_SIZE, color: '#d7cdb8' },
    { id: 'aisle-runner', name: '入室引导毯', type: 'decoration', x: 11.55 * TILE_SIZE, y: 0.92 * TILE_SIZE, w: 2.9 * TILE_SIZE, h: 1.7 * TILE_SIZE, color: 'rgba(111, 127, 114, 0.16)' },
    { id: 'stacks-door-glow', name: '藏书室门前光晕', type: 'decoration', x: 12.85 * TILE_SIZE, y: 0.9 * TILE_SIZE, w: 2.1 * TILE_SIZE, h: 1.95 * TILE_SIZE, color: 'rgba(255,255,255,0.09)' },
    { id: 'stacks-aisle-guide', name: '馆藏导引线', type: 'decoration', x: 12.9 * TILE_SIZE, y: 2.65 * TILE_SIZE, w: 0.12 * TILE_SIZE, h: 5.25 * TILE_SIZE, color: 'rgba(111, 127, 114, 0.12)' },
    { id: 'reading-note-glow', name: '桌上便签光晕', type: 'decoration', x: 8.05 * TILE_SIZE, y: 4.28 * TILE_SIZE, w: 1.65 * TILE_SIZE, h: 1 * TILE_SIZE, color: 'rgba(255,255,255,0.08)' },
    { id: 'left-lamp-glow', name: '灯影', type: 'decoration', x: 5.2 * TILE_SIZE, y: 4.2 * TILE_SIZE, w: 1.3 * TILE_SIZE, h: 1.3 * TILE_SIZE, color: 'rgba(255,255,255,0.12)' },
    { id: 'right-lamp-glow', name: '灯影', type: 'decoration', x: 11.4 * TILE_SIZE, y: 4.2 * TILE_SIZE, w: 1.3 * TILE_SIZE, h: 1.3 * TILE_SIZE, color: 'rgba(255,255,255,0.12)' },
    { id: 'catalog-placard', name: '总目录签条', type: 'decoration', x: 2.2 * TILE_SIZE, y: 1.25 * TILE_SIZE, w: 1.45 * TILE_SIZE, h: 0.38 * TILE_SIZE, color: '#d8c5aa' },
    { id: 'stacks-placard', name: '藏书室门牌', type: 'decoration', x: 13.85 * TILE_SIZE, y: 1.25 * TILE_SIZE, w: 1.95 * TILE_SIZE, h: 0.38 * TILE_SIZE, color: '#d8c5aa' },
    { id: 'stacks-guide-card', name: '馆藏导览牌', type: 'decoration', x: 14.0 * TILE_SIZE, y: 1.72 * TILE_SIZE, w: 1.7 * TILE_SIZE, h: 0.62 * TILE_SIZE, color: '#e2d6c5' },
    { id: 'entry-axis-runner', name: '阅览入室导引带', type: 'decoration', x: 7.55 * TILE_SIZE, y: 7.2 * TILE_SIZE, w: 1.05 * TILE_SIZE, h: 3.55 * TILE_SIZE, color: 'rgba(111, 127, 114, 0.12)' },
    { id: 'reading-axis-strip', name: '阅览中轴线', type: 'decoration', x: 8.95 * TILE_SIZE, y: 4.15 * TILE_SIZE, w: 0.12 * TILE_SIZE, h: 3.1 * TILE_SIZE, color: 'rgba(126, 104, 86, 0.12)' },
    { id: 'north-light-wash', name: '上部窗影', type: 'decoration', x: 12.55 * TILE_SIZE, y: 1.12 * TILE_SIZE, w: 2.65 * TILE_SIZE, h: 1.15 * TILE_SIZE, color: 'rgba(255,255,255,0.06)' },
  ],
  obstacles: [
    { id: 'left-wall', name: '左墙', type: 'obstacle', x: 0, y: 0, w: TILE_SIZE, h: 12 * TILE_SIZE, color: '#85705f' },
    { id: 'right-wall', name: '右墙', type: 'obstacle', x: 17 * TILE_SIZE, y: 0, w: TILE_SIZE, h: 12 * TILE_SIZE, color: '#85705f' },
    { id: 'top-left-wall', name: '上墙左', type: 'obstacle', x: 0, y: 0, w: 6 * TILE_SIZE, h: TILE_SIZE, color: '#85705f' },
    { id: 'top-mid-wall', name: '上墙中', type: 'obstacle', x: 8 * TILE_SIZE, y: 0, w: 4 * TILE_SIZE, h: TILE_SIZE, color: '#85705f' },
    { id: 'top-right-wall', name: '上墙右', type: 'obstacle', x: 14 * TILE_SIZE, y: 0, w: 4 * TILE_SIZE, h: TILE_SIZE, color: '#85705f' },
    { id: 'bottom-left', name: '下墙左', type: 'obstacle', x: 0, y: 11 * TILE_SIZE, w: 7 * TILE_SIZE, h: TILE_SIZE, color: '#85705f' },
    { id: 'bottom-right', name: '下墙右', type: 'obstacle', x: 9 * TILE_SIZE, y: 11 * TILE_SIZE, w: 9 * TILE_SIZE, h: TILE_SIZE, color: '#85705f' },
    { id: 'catalog-cabinet', name: '目录柜', type: 'obstacle', x: 2.2 * TILE_SIZE, y: 1.65 * TILE_SIZE, w: 1.5 * TILE_SIZE, h: 2.1 * TILE_SIZE, color: '#92735c' },
    { id: 'stacks-frame', name: '门框', type: 'obstacle', x: 13.8 * TILE_SIZE, y: 1.65 * TILE_SIZE, w: 1.9 * TILE_SIZE, h: 2.1 * TILE_SIZE, color: '#92735c' },
    { id: 'reading-table', name: '阅览桌', type: 'obstacle', x: 6.8 * TILE_SIZE, y: 5.05 * TILE_SIZE, w: 4.2 * TILE_SIZE, h: 2 * TILE_SIZE, color: '#aa8a6d' },
    { id: 'left-bench', name: '长椅', type: 'obstacle', x: 3.2 * TILE_SIZE, y: 8.15 * TILE_SIZE, w: 2 * TILE_SIZE, h: 1.05 * TILE_SIZE, color: '#987a61' },
    { id: 'right-bench', name: '长椅', type: 'obstacle', x: 12.8 * TILE_SIZE, y: 8.15 * TILE_SIZE, w: 2 * TILE_SIZE, h: 1.05 * TILE_SIZE, color: '#987a61' },
    { id: 'return-cart', name: '归还车', type: 'obstacle', x: 12.7 * TILE_SIZE, y: 8.45 * TILE_SIZE, w: 1.55 * TILE_SIZE, h: 1.05 * TILE_SIZE, color: '#b18f72' },
  ],
  interactables: [
    {
      id: 'back-door',
      name: '返回大厅',
      type: 'interactable',
      x: 7 * TILE_SIZE,
      y: 11 * TILE_SIZE,
      w: 2 * TILE_SIZE,
      h: TILE_SIZE,
      color: '#6f7f72',
      prompt: 'E 返回大厅',
      action: { kind: 'scene', toSceneId: 'hall', spawnId: 'fromLibrary' }
    },
    {
      id: 'catalog-board',
      name: '总目录卡柜',
      type: 'interactable',
      x: 2.25 * TILE_SIZE,
      y: 1.26 * TILE_SIZE,
      w: 1.4 * TILE_SIZE,
      h: 0.38 * TILE_SIZE,
      color: '#d5c4ad',
      prompt: 'E 打开馆藏目录',
      action: { kind: 'route', to: '/catalog' },
      hitbox: { x: 0, y: 0, w: 0, h: 0 },
      interactbox: { x: 2.1 * TILE_SIZE, y: 1.2 * TILE_SIZE, w: 1.75 * TILE_SIZE, h: 2.65 * TILE_SIZE },
    },
    {
      id: 'stacks-door',
      name: '藏书室门',
      type: 'interactable',
      x: 12 * TILE_SIZE,
      y: 0,
      w: 2 * TILE_SIZE,
      h: TILE_SIZE,
      color: '#6f7f72',
      prompt: 'E 进入藏书室',
      action: { kind: 'scene', toSceneId: 'stacks', spawnId: 'entry' }
    },
    {
      id: 'stacks-note',
      name: '藏书室门牌',
      type: 'interactable',
      x: 13.9 * TILE_SIZE,
      y: 1.25 * TILE_SIZE,
      w: 1.7 * TILE_SIZE,
      h: 0.38 * TILE_SIZE,
      color: '#d5c4ad',
      prompt: 'E 查看藏书室导览',
      action: { kind: 'dialog', dialogId: 'stackDoor' },
      hitbox: { x: 0, y: 0, w: 0, h: 0 },
      interactbox: { x: 13.75 * TILE_SIZE, y: 1.2 * TILE_SIZE, w: 2.1 * TILE_SIZE, h: 2.1 * TILE_SIZE },
    },
    {
      id: 'reading-desk-note',
      name: '阅览桌便签',
      type: 'interactable',
      x: 8.25 * TILE_SIZE,
      y: 4.45 * TILE_SIZE,
      w: 1.2 * TILE_SIZE,
      h: 0.8 * TILE_SIZE,
      color: '#d9c7b0',
      prompt: 'E 查看阅览桌',
      action: { kind: 'dialog', dialogId: 'libraryDesk' },
      hitbox: { x: 0, y: 0, w: 0, h: 0 },
      interactbox: { x: 8 * TILE_SIZE, y: 4.35 * TILE_SIZE, w: 1.6 * TILE_SIZE, h: 1.05 * TILE_SIZE },
    },
  ],
};
